### ISSUE TITLE
Still this relevant?

### ISSUE THREAD

**Issue by winferr** [kriogenic/Hades-Twitch-Integration#4]
Is this project still relevant? 
Im tried different versions of modimporter and also modUtil but other mods works fine. 
When trying to install Twitch integration mod game doesn't give me load my save.
Can I do something to let this mod work or it's need update?

Thanks :)

**Comment by kriogenic** [comment]
It is out of date at this time. I will try find time to get it fixed hopefully in the next month or so
You also MUST run Hades in 32 bit mode for this mod to work correctly, maybe try that and see if it works for you
